Create simple motion capture relay node for the demo
ArthurH91/panda_torque_mpc pull request #12
Opened 2024-02-12 12:53 UTC by Kotochleb

2024-02-12 13:47 UTC, ArthurH91 requested changes
good

2024-02-12 13:47 UTC, ArthurH91 commented on nodes/motion_capture_relay.py
> +                f"[{rospy.get_name()}] Param ~sphere_radious not fount, but required. Shutting down!"
```suggestion
                f"[{rospy.get_name()}] Param ~sphere_radious not found, but required. Shutting down!"
```

2024-02-12 13:47 UTC, ArthurH91 commented on README.md
> +
```suggestion
Select `motion_capture.launch` parameter `relay` to **false** to create fake motion capture input data.

```

2024-06-27 14:57 UTC, MedericFourmy commented
Should this be closed after the coding week work?

2024-07-02 10:26 UTC, Kotochleb commented
@MedericFourmy definitively this should be closed as it is redundant to the https://github.com/agimus-project/panda_torque_mpc/pull/10 which is also currently developed fork

2024-07-02 10:26 UTC, closed without merging