Bugfix/length error
ArthurH91/panda_torque_mpc pull request #14
Opened 2024-03-04 15:58 UTC by ArthurH91

2024-03-04 21:53 UTC, Kotochleb requested changes
Please remove the unnecessary prints you used for debug

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +            std::cout << "not right: " << std::endl;
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +            std::cout << "not right1: " << std::endl;
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on include/panda_torque_mpc/common.h
> +
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +            std::cout << "not right2: " << std::endl;
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +            std::cout << "not right3: " << std::endl;
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +            std::cout << "not right4: " << std::endl;
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +            std::cout << "not right5: " << std::endl;
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +            std::cout << "not right61: " << std::endl;
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +            boost::shared_ptr<pinocchio::GeometryModel> collision_model = boost::make_shared<pinocchio::GeometryModel>();
```suggestion
            auto collision_model = boost::make_shared<pinocchio::GeometryModel>();
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +            std::cout << "not right64: " << std::endl;
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +            std::cout << "not right7: " << std::endl;
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +            std::cout << "not right8: " << std::endl;
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +            std::cout << "not right9: " << std::endl;
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +    std::cout << "OK1: "<< std::endl;
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on src/crocoddyl_motion_server_node.cpp
> +
```suggestion
```

2024-03-04 21:53 UTC, Kotochleb commented on include/panda_torque_mpc/common.h
> +        std::string urdf_path = ros::package::getPath("panda_torque_mpc") + "/urdf/robot.urdf";
```suggestion
        const std::string urdf_path = ros::package::getPath("panda_torque_mpc") + "/urdf/robot.urdf";
```
The value of this variable is not supposed to change later on, so it is better to keep it as a constant

2024-03-04 21:53 UTC, Kotochleb commented on include/panda_torque_mpc/common.h
> +    inline boost::shared_ptr<pinocchio::GeometryModel> loadPandaGeometryModel(pinocchio::Model model_pin)
```suggestion
    inline boost::shared_ptr<pinocchio::GeometryModel> loadPandaGeometryModel(const pinocchio::Model& model_pin)
```
Non-mutable parameters should always be constant. Also, anything that is not a fundamental type should be passed by refference

2024-03-05 14:32 UTC, ArthurH91 commented
ready to merge @Kotochleb , it works after building ir.

2024-03-05 14:38 UTC, Kotochleb approved these changes

2024-03-05 14:38 UTC, merged